services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SPRING_SERVER_PORT}:${SPRING_SERVER_PORT}"
    env_file:
      - .env
    environment:
      - SPRING_SERVER_PORT=${SPRING_SERVER_PORT}
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DEVTOOLS_RESTART_ENABLED=${SPRING_DEVTOOLS_RESTART_ENABLED}
      - SPRING_DEVTOOLS_RESTART_EXCLUDE=${SPRING_DEVTOOLS_RESTART_EXCLUDE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=${SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}
      - SPRING_MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=${SPRING_MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
      - SPRING_LOGGING_LEVEL_COM_AUTH_SERVICE=${SPRING_LOGGING_LEVEL_COM_AUTH_SERVICE}
      - SPRING_JWT_SECRET=${SPRING_JWT_SECRET}
      - SPRING_DOC_API_DOCS_PATH=${SPRING_DOC_API_DOCS_PATH}
      - SPRING_DOC_SWAGGER_UI_PATH=${SPRING_DOC_SWAGGER_UI_PATH}
    depends_on:
      - db